### ISSUE TITLE
Help with route plugin

### ISSUE THREAD

**Issue by handiworknyc** [swup/route-name-plugin#1]
Hi @gmrchk hoping you can help me.

I'm using wordpress.

My URL structure is :
`http://localhost:8888/cdw/work/telesign/`
`http://localhost:8888/cdw/work/foo/`
`http://localhost:8888/cdw/work/bar/`
`http://localhost:8888/cdw/work/etc/`

I just want to assign the route name "work" to any URL containing work.
![image](https://user-images.githubusercontent.com/76538523/191337417-c726ca58-3500-4753-a38b-058351a267c6.png)

None of these are working though:
```
			routes: [
				{ name: 'work', path: '/work/:slug' },
			]
```

not working:

```
			routes: [
				{ name: 'work', path: '/work/(.*)' },
			]
```

Please help! thanks

**Comment by daun** [comment]
Your routes all start with `cdw`, the path definitions should start with `/cdw/work`.

**Comment by handiworknyc** [comment]
Thank you!!!! That was too obvious

**Comment by daun** [comment]
Great!
